### ISSUE TITLE
[BUG] Updating fishstrap doesnt override older version

### ISSUE THREAD

**Issue by NoobLikesThis** [returnrqt/fishstrap#1]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0.2

### What problem did you encounter?

when i tried updating fishstrap, it did not override the old version of v2.8.0 while downloading 2.8.1.3.

### Bloxstrap Log

```text
N/A
```

**Comment by returnrqt** [comment]
Hi,
I tried replicating the issue on my device. I was able to upgrade from 2.8.0.2 to 2.8.1.3 without the issue.
Can you check if Fishstrap v2.8.0.2 was installed in `%localappdata%\Fishstrap`?

**Comment by SatlyBPro** [comment]
Try closing any Bloxstrap/Fishstrap related process from task manager then executing the new version's .exe file, I had the same issue but closing all processes was what fixed the issue for me, if this doesn't work, I don't have any other ideas.

**Comment by NoobLikesThis** [comment]
i did

**Comment by SatlyBPro** [comment]
Can you tell me what happened when you ran the v2.8.0.13 `.exe` file that updates to the new version? Did it prompt you to that you're going to override the old version with a yes or no button, and if you clicked yes what happened after? And how are you launching the new version? Any other information would be helpful.

**Comment by NoobLikesThis** [comment]
i pressed yes, clicked off the old one  and it sent me on the new one, but when i when to fishstrap again, it was on the old version.

**Comment by SatlyBPro** [comment]
Try deleting the old shortcut, then closing all processes from task manager, updating again, then in the window that pops up after you finish click "Configure settings" then from there go and create a new desktop shortcut for Fishstrap Settings, then try again and let me know what happened.

**Comment by NoobLikesThis** [comment]
o, i deleted fishstrap for it to work so i cant now.
