### ISSUE TITLE
[BUG] just downloaded fishstrap, now im getting this error

### ISSUE THREAD

**Issue by apexpredatrr** [returnrqt/fishstrap#11]
### Fishstrap Version

v2.8.1.5

### What problem did you encounter?

so i decided to download fishstrap because why not and now im getting this
![image](https://github.com/user-attachments/assets/8eb1c648-8aaf-42ba-8b0b-72e29a1cf04e)

**Comment by apexpredatrr** [comment]
as it turns out, it doesnt let me use the live channel for some reason

**Comment by netsoftwork** [comment]
its called the production channel

**Comment by netsoftwork** [comment]
production = live

**Comment by d44df016fe28bc8d5974** [comment]
stop trying to use live
live doesn't work on fishstrap 
you have to use production, and production is live but with a different name

**Comment by apexpredatrr** [comment]
oohh, thank you
