### ISSUE TITLE
[BUG] Roblox Studio is not launched with the correct arguments

### ISSUE THREAD

**Issue by bitceil** [returnrqt/fishstrap#12]
### Fishstrap Version

latest

### What problem did you encounter?

when launching stuff with the Roblox Studio thats managed by Fishstrap, no matter what it just opens the home page. these issues happen when: you click edit on the roblox website for a place & when attempting to open place files

### Bloxstrap Log

```text
N/A
```

**Comment by returnrqt** [comment]
Does the same happen with Bloxstrap?

**Comment by bitceil** [comment]
i mean, as far as i know. bloxstrap doesnt manage Studio at at all.

**Comment by d44df016fe28bc8d5974** [comment]
> Does the same happen with Bloxstrap?

this issue is real
it happens to me too

**Comment by returnrqt** [comment]
> i mean, as far as i know. bloxstrap doesnt manage Studio at at all.

It does. Start Bloxstrap with -s argument.

**Comment by bitceil** [comment]
oh well i didnt really know about it, ill submit a bug report to bloxstrap
(edit: looks like they already have it reported.)

**Comment by bitceil** [comment]
closed.
