### ISSUE TITLE
[QUESTION] how do u create exe files bc me stupid with 10 iq

### ISSUE THREAD

**Issue by NoobLikesThis** [returnrqt/fishstrap#13]
how u create exe files for fishstrap

**Comment by returnrqt** [comment]
You need to compile the program. Here's Bloxstrap wiki page about it
https://github.com/bloxstraplabs/bloxstrap/wiki/Building-Bloxstrap-from-source

Also please remember Github issues are for reporting bugs and requesting features.
For any questions join Fishstrap discord server.
