### ISSUE TITLE
[REQ] Test mode improvements

### ISSUE THREAD

**Issue by NotValra** [returnrqt/fishstrap#16]
### What idea do you have?

It would be really nice if test mode opened up on the page that it was on before fishstrap closed. For example if im editing fast flags and then i used the test mode to open roblox, then after closing roblox fishstrap would automatically open up on the fast flag page

**Comment by returnrqt** [comment]
Sure. Once I finish custom themes.

**Comment by NotValra** [comment]
OO thanks :DDDDDDDD

**Comment by returnrqt** [comment]
Added.
