### ISSUE TITLE
[BUG] got softlocked

### ISSUE THREAD

**Issue by SANS3R66** [returnrqt/fishstrap#17]
### Fishstrap Version

v2.8.1.5

### What problem did you encounter?

now i cant nor redownload roblox nor update it :sob:
![image](https://github.com/user-attachments/assets/6a79c856-3418-4854-bcaa-bcc88b0115d4)

### Bloxstrap Log

```text
N/A
```

**Comment by returnrqt** [comment]
Try deleting your setting.json file.

**Comment by SANS3R66** [comment]
no
