### ISSUE TITLE
[BUG] Fishstrap automatically closing

### ISSUE THREAD

**Issue by Zestfest1** [returnrqt/fishstrap#18]
### Fishstrap Version

v2.8.1.5

### What problem did you encounter?

For some reason when i try launching fishstrap it automatically closes. i tries using test mode and when i launch it just puts me in settings. please help

### Bloxstrap Log

```text
N/A
```

**Comment by returnrqt** [comment]
Can you check if you're using vulkan rendering?

**Comment by Zestfest1** [comment]
Yes I am using vulkan settings. I changed do direct3D 10 and 11 and OpenGL but those also didnt do anything. Ive been told to uninstall bloxstrap and i did that but still dont work :C

**Comment by returnrqt** [comment]
Sounds like a client issue. Can you try removing all of your feature flags?

**Comment by Zestfest1** [comment]
I did that and switched to direct3D 10 and it now works, ty!
