### ISSUE TITLE
System.IO.IOException

### ISSUE THREAD

**Issue by BoniBonQ** [returnrqt/fishstrap#19]
### Fishstrap Version

v2.8.1.5

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/f70504f3-776c-48e0-b427-379c25265231)

Just look at the screenshot. I have no idea what it means. I just need help. It has been like this for 3 days, and I can't use Fishtrap because I always get this error.

thank you

**Comment by returnrqt** [comment]
Can you please send me a log file?
