### ISSUE TITLE
[REQ] Any plans on adding the custom themes from the original bloxstrap actions build (which stayed in beta and isnt released cause pizzaboxer left.)

### ISSUE THREAD

**Issue by user1126s** [returnrqt/fishstrap#20]
### What idea do you have?

![image](https://github.com/user-attachments/assets/6c99aa53-9143-4305-9745-f51d4efa16a4)
im talking about this. if you want i can share all the themes that were made by various people before the channel got removed and all the themes with it but i managed to save all except maybe like 2. 
![image](https://github.com/user-attachments/assets/316863d2-941b-4a4f-b9d2-9ebc15863d99)
build info (i have auto update on otherwise it auto updates to stable)
please add this feature and i can provide a themelist with downloads and instructions on how to make and how to import. Thanks :D
happy holidays!

**Comment by d44df016fe28bc8d5974** [comment]
this is already a thing you just have to download a [dev build ](https://github.com/returnrqt/fishstrap/actions/runs/12359683802)

**Comment by d44df016fe28bc8d5974** [comment]
can you also share the themes that you saved

**Comment by user1126s** [comment]
the themes are alot lol
[2015Loading.zip](https://github.com/user-attachments/files/18265144/2015Loading.zip)
[Adobe Bootstrap.zip](https://github.com/user-attachments/files/18265146/Adobe.Bootstrap.zip)
[BloxShop 2025.zip](https://github.com/user-attachments/files/18265147/BloxShop.2025.zip)
[BloxShop CC 2017.zip](https://github.com/user-attachments/files/18265148/BloxShop.CC.2017.zip)
[Dreamwaver 2021.zip](https://github.com/user-attachments/files/18265149/Dreamwaver.2021.zip)
[Jasperblox.zip](https://github.com/user-attachments/files/18265150/Jasperblox.zip)
[MrDino.zip](https://github.com/user-attachments/files/18265151/MrDino.zip)
[Roffice.zip](https://github.com/user-attachments/files/18265152/Roffice.zip)
[Solidworks.zip](https://github.com/user-attachments/files/18265153/Solidworks.zip)
[Steam.zip](https://github.com/user-attachments/files/18265154/Steam.zip)
[Themes2.zip](https://github.com/user-attachments/files/18265155/Themes2.zip)
[WhatsStrap 📞.zip](https://github.com/user-attachments/files/18265156/WhatsStrap.zip)
do not add these, i will, first lemme ask for their creator's perms

**Comment by Skylan031** [comment]
There are no plans for including custom bootstrappers as a preset, it's up to you to create/find them
