### ISSUE TITLE
[BUG] fishstrap (glass) doesnt work

### ISSUE THREAD

**Issue by NoobLikesThis** [returnrqt/fishstrap#3]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1.4

### glass:
![image](https://github.com/user-attachments/assets/07c59b1e-cdb4-4a5c-a7f3-0ec2baf711ba)
### normal:
![image](https://github.com/user-attachments/assets/3d193620-1bdb-42aa-bd1d-f9720a07ac25)
### with transparency:
![image](https://github.com/user-attachments/assets/cebb482f-0ab1-46be-8e07-ace83345e4a9)
![image](https://github.com/user-attachments/assets/44965711-0792-4477-9b98-ce02beeff388)

### Bloxstrap Log

```text
N/A
```

**Comment by returnrqt** [comment]
Hi,
Could you check if it's happening in Bloxstrap too?
Thanks.

**Comment by NoobLikesThis** [comment]
> Hi, Could you check if it's happening in Bloxstrap too? Thanks.

prob not, i had transparency off in bloxstrap and  i saw it ages ago. (i dont mean the transparent background)

**Comment by d44df016fe28bc8d5974** [comment]
this is probably a issue with your pc
i have transparency effects disabled and the glass theme works

**Comment by NoobLikesThis** [comment]
> this is probably a issue with your pc i have transparency effects disabled and the glass theme works

u  using windows 11?

**Comment by d44df016fe28bc8d5974** [comment]
windows 10

**Comment by NoobLikesThis** [comment]
settings -> personalization -> colours
