### ISSUE TITLE
[REQ] disabling features depending on your enabled features

### ISSUE THREAD

**Issue by NoobLikesThis** [returnrqt/fishstrap#4]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### preview:
![image](https://github.com/user-attachments/assets/51b34aa7-2b90-417b-9d2c-e55462ca1c28)
![image](https://github.com/user-attachments/assets/d6f839ae-685f-4d50-a6b7-f89970ff39f7)

**Comment by returnrqt** [comment]
I'll change that next version. Thanks for requesting.
