### ISSUE TITLE
[BUG] flag profiles dont work

### ISSUE THREAD

**Issue by NoobLikesThis** [returnrqt/fishstrap#7]
### Fishstrap Version

v2.8.1.5

### What problem did you encounter?

when trying to use a flag profile, it wont work.
i am  using windows 11.

### Bloxstrap Log

```text
N/A
```

**Comment by d44df016fe28bc8d5974** [comment]
what preset

**Comment by NoobLikesThis** [comment]
i called it preset didnt i?
translation: i was being an idiot

**Comment by returnrqt** [comment]
What presets aren't working for you?

**Comment by returnrqt** [comment]
Oh

**Comment by returnrqt** [comment]
What's wrong with the profiles?

**Comment by NoobLikesThis** [comment]
> What's wrong with the profiles?

dont load.
doing ctrl click to delete multiple flag  profiles dont work either.

**Comment by NoobLikesThis** [comment]
somehow got this with snipping tool
![image](https://github.com/user-attachments/assets/dbfb90f7-a507-44e8-9347-80be2a6ae976)

**Comment by returnrqt** [comment]
Could you check flag profiles folder in Fishstrap installation folder?

**Comment by NoobLikesThis** [comment]
> Could you check flag profiles folder in Fishstrap installation folder?

sure, i normally delete fishstrap and add my presets back, may be the problem of me not deleting fishstrap this time.

**Comment by NoobLikesThis** [comment]
> Could you check flag profiles folder in Fishstrap installation folder?

for what?

**Comment by returnrqt** [comment]
> > What's wrong with the profiles?
> 
> dont load.
> doing ctrl click to delete multiple flag  profiles dont work either.

You've said flag profiles aren't loading. Try checking if any exist in the first place.

**Comment by NoobLikesThis** [comment]
![image](https://github.com/user-attachments/assets/9c02a9ef-f3b5-448c-a9bd-3b4837a7396a)
 think so

**Comment by returnrqt** [comment]
Load page is just empty?

**Comment by d44df016fe28bc8d5974** [comment]
> ![image](https://private-user-images.githubusercontent.com/181637537/386873979-9c02a9ef-f3b5-448c-a9bd-3b4837a7396a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODY4ODgsIm5iZiI6MTczMTc4NjU4OCwicGF0aCI6Ii8xODE2Mzc1MzcvMzg2ODczOTc5LTljMDJhOWVmLWYzYjUtNDQ4Yy1hOWJkLTNiNDgzN2E3Mzk2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxOTQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTE1ODg0MmJlMDYxYTExOTY5MTUzMmI3NDgxOWI3OTkxMzQ3YTQxODk2MTAzYzBmN2MzMDVkMjdlOWRjMDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hccDor-gz2XldHbSPEcgf_tPyTm7BZ6UD7mGUXioti4) 
think so
shouldn't the flag profiles be in .json

**Comment by NoobLikesThis** [comment]
huh, could be just my laggy pc then

**Comment by NoobLikesThis** [comment]
https://github.com/user-attachments/assets/205ade88-358e-4c7f-84ff-3dbd85cf42a0

**Comment by d44df016fe28bc8d5974** [comment]
check clientappsettings.json if they were added

**Comment by NoobLikesThis** [comment]
> check clientappsettings.json if they were added

good idea, but didnt update it.
