### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'D:\FishTrap\Roblox\Player\ucrtbase.dll' is denied.

### ISSUE THREAD

**Issue by Danishtzy24** [returnrqt/fishstrap#8]
### Fishstrap Version

2.8.1.5

### What problem did you encounter?

Cant Lunch Roblox

### Bloxstrap Log

```text
N/A
```

**Comment by returnrqt** [comment]
Can you send Fishstrap log file?

**Comment by Danishtzy24** [comment]
[Uploading erorr.txt…]()

**Comment by Danishtzy24** [comment]
[Fishstrap_20241120T114216Z.log](https://github.com/user-attachments/files/17829998/Fishstrap_20241120T114216Z.log)

**Comment by returnrqt** [comment]
Thank you for submitting a bug report. I'll try to replicate it on my device later.
